"""
schema.py – Elastic integration-compatible index templates and component templates
for the agent-intrusion-lab workshop.  The field mappings mirror exactly what the
Elasticsearch Kubernetes Audit Logs integration and AWS CloudTrail integration
produce so that the 36 prebuilt Elastic Security detection rules fire on the
synthetic data generated by the lab's event generators.
"""

from __future__ import annotations

import logging
from typing import Any

logger = logging.getLogger(__name__)

DS_NAMESPACE = "workshop"

# ---------------------------------------------------------------------------
# Component templates
# ---------------------------------------------------------------------------

COMPONENT_TEMPLATES: list[dict[str, Any]] = [
    # ------------------------------------------------------------------
    # Base: epoch_millis @timestamp + data_stream fields shared by all
    # ------------------------------------------------------------------
    {
        "name": "lab-base@mappings",
        "body": {
            "template": {
                "mappings": {
                    "dynamic": True,
                    "dynamic_date_formats": ["strict_date_optional_time||epoch_millis"],
                    "properties": {
                        "@timestamp": {
                            "type": "date",
                            "format": "strict_date_optional_time||epoch_millis",
                        },
                        "data_stream": {
                            "properties": {
                                "dataset":    {"type": "constant_keyword"},
                                "namespace":  {"type": "constant_keyword"},
                                "type":       {"type": "constant_keyword", "value": "logs"},
                            }
                        },
                        "event": {
                            "properties": {
                                "dataset":   {"type": "keyword"},
                                "action":    {"type": "keyword"},
                                "outcome":   {"type": "keyword"},
                                "category":  {"type": "keyword"},
                                "type":      {"type": "keyword"},
                                "provider":  {"type": "keyword"},
                                "ingested":  {
                                    "type": "date",
                                    "format": "strict_date_optional_time||epoch_millis",
                                },
                            }
                        },
                        "source": {
                            "properties": {
                                "ip":      {"type": "ip"},
                                "address": {"type": "keyword"},
                                "as": {
                                    "properties": {
                                        "number":               {"type": "long"},
                                        "organization": {
                                            "properties": {
                                                "name": {"type": "keyword"}
                                            }
                                        },
                                    }
                                },
                                "geo": {
                                    "properties": {
                                        "city_name":    {"type": "keyword"},
                                        "country_name": {"type": "keyword"},
                                    }
                                },
                            }
                        },
                        "user": {
                            "properties": {
                                "name": {"type": "keyword"},
                                "id":   {"type": "keyword"},
                            }
                        },
                        "user_agent": {
                            "properties": {
                                "original": {"type": "keyword"},
                                "name":     {"type": "keyword"},
                            }
                        },
                        "cloud": {
                            "properties": {
                                "account": {
                                    "properties": {
                                        "id": {"type": "keyword"}
                                    }
                                },
                                "region": {"type": "keyword"},
                            }
                        },
                        "host": {
                            "properties": {
                                "os": {
                                    "properties": {
                                        "type": {"type": "keyword"}
                                    }
                                }
                            }
                        },
                        "container": {
                            "properties": {
                                "id": {"type": "keyword"}
                            }
                        },
                        "tags":    {"type": "keyword"},
                        "message": {"type": "text"},
                    },
                }
            }
        },
    },

    # ------------------------------------------------------------------
    # Kubernetes audit_logs component
    # ------------------------------------------------------------------
    {
        "name": "lab-kubernetes.audit_logs@mappings",
        "body": {
            "template": {
                "mappings": {
                    "properties": {
                        "orchestrator": {
                            "properties": {
                                "cluster": {
                                    "properties": {
                                        "name": {"type": "keyword"}
                                    }
                                },
                                "resource": {
                                    "properties": {
                                        "name": {"type": "keyword"}
                                    }
                                },
                            }
                        },
                        "kubernetes": {
                            "properties": {
                                "audit": {
                                    "properties": {
                                        "verb":       {"type": "keyword"},
                                        "stage":      {"type": "keyword"},
                                        "level":      {"type": "keyword"},
                                        "requestURI": {"type": "keyword"},
                                        "sourceIPs":  {"type": "keyword"},
                                        "objectRef": {
                                            "properties": {
                                                "resource":    {"type": "keyword"},
                                                "subresource": {"type": "keyword"},
                                                "namespace":   {"type": "keyword"},
                                                "name":        {"type": "keyword"},
                                            }
                                        },
                                        "user": {
                                            "properties": {
                                                "username": {"type": "keyword"},
                                                "groups":   {"type": "keyword"},
                                                "extra": {
                                                    "properties": {
                                                        # The real integration flattens extra as a nested object;
                                                        # using flattened here handles arbitrary key names.
                                                        "authentication.kubernetes.io/pod-name": {
                                                            "type": "keyword"
                                                        }
                                                    }
                                                },
                                            }
                                        },
                                        "impersonatedUser": {
                                            "properties": {
                                                "username": {"type": "keyword"}
                                            }
                                        },
                                        "annotations": {
                                            "properties": {
                                                # The literal slash is part of the Kubernetes annotation key.
                                                "authorization_k8s_io/decision": {"type": "keyword"},
                                                "authorization_k8s_io/reason":   {"type": "keyword"},
                                            }
                                        },
                                        "requestObject": {
                                            "properties": {
                                                "spec": {
                                                    "properties": {
                                                        "hostNetwork": {"type": "boolean"},
                                                        "hostPID":     {"type": "boolean"},
                                                        "hostIPC":     {"type": "boolean"},
                                                        "serviceAccountName": {"type": "keyword"},
                                                        "containers": {
                                                            "type": "nested",
                                                            "properties": {
                                                                "image": {"type": "keyword"},
                                                                "name":  {"type": "keyword"},
                                                                "securityContext": {
                                                                    "properties": {
                                                                        "privileged": {"type": "boolean"},
                                                                        "capabilities": {
                                                                            "properties": {
                                                                                "add":  {"type": "keyword"},
                                                                                "drop": {"type": "keyword"},
                                                                            }
                                                                        },
                                                                        "allowPrivilegeEscalation": {
                                                                            "type": "boolean"
                                                                        },
                                                                        "runAsUser":  {"type": "long"},
                                                                        "runAsGroup": {"type": "long"},
                                                                    }
                                                                },
                                                            },
                                                        },
                                                        "initContainers": {
                                                            "type": "nested",
                                                            "properties": {
                                                                "image": {"type": "keyword"},
                                                                "name":  {"type": "keyword"},
                                                                "securityContext": {
                                                                    "properties": {
                                                                        "privileged": {"type": "boolean"},
                                                                        "capabilities": {
                                                                            "properties": {
                                                                                "add":  {"type": "keyword"},
                                                                                "drop": {"type": "keyword"},
                                                                            }
                                                                        },
                                                                    }
                                                                },
                                                            },
                                                        },
                                                        "volumes": {
                                                            "type": "nested",
                                                            "properties": {
                                                                "name": {"type": "keyword"},
                                                                "hostPath": {
                                                                    "properties": {
                                                                        "path": {"type": "keyword"},
                                                                        "type": {"type": "keyword"},
                                                                    }
                                                                },
                                                            },
                                                        },
                                                    }
                                                },
                                                "roleRef": {
                                                    "properties": {
                                                        "apiGroup": {"type": "keyword"},
                                                        "kind":     {"type": "keyword"},
                                                        "name":     {"type": "keyword"},
                                                    }
                                                },
                                                "subjects": {
                                                    "type": "nested",
                                                    "properties": {
                                                        "kind":      {"type": "keyword"},
                                                        "name":      {"type": "keyword"},
                                                        "namespace": {"type": "keyword"},
                                                    },
                                                },
                                                "rules": {
                                                    "type": "nested",
                                                    "properties": {
                                                        "apiGroups": {"type": "keyword"},
                                                        "resources": {"type": "keyword"},
                                                        "verbs":     {"type": "keyword"},
                                                    },
                                                },
                                            }
                                        },
                                        "responseObject": {
                                            "properties": {
                                                "rules": {
                                                    "type": "nested",
                                                    "properties": {
                                                        "apiGroups": {"type": "keyword"},
                                                        "resources": {"type": "keyword"},
                                                        "verbs":     {"type": "keyword"},
                                                    },
                                                },
                                                "status": {
                                                    "properties": {
                                                        "phase": {"type": "keyword"},
                                                    }
                                                },
                                            }
                                        },
                                        "responseStatus": {
                                            "properties": {
                                                "code":    {"type": "integer"},
                                                "status":  {"type": "keyword"},
                                                "message": {"type": "keyword"},
                                            }
                                        },
                                    }
                                }
                            }
                        },
                    }
                }
            }
        },
    },

    # ------------------------------------------------------------------
    # AWS CloudTrail component
    # ------------------------------------------------------------------
    {
        "name": "lab-aws.cloudtrail@mappings",
        "body": {
            "template": {
                "mappings": {
                    "properties": {
                        "aws": {
                            "properties": {
                                "cloudtrail": {
                                    "properties": {
                                        "event_category":               {"type": "keyword"},
                                        "error_code":                   {"type": "keyword"},
                                        "error_message":                {"type": "keyword"},
                                        "session_credential_from_console": {"type": "keyword"},
                                        "user_identity": {
                                            "properties": {
                                                "type":          {"type": "keyword"},
                                                "arn":           {"type": "keyword"},
                                                "access_key_id": {"type": "keyword"},
                                                "account_id":    {"type": "keyword"},
                                                "session_context": {
                                                    "properties": {
                                                        "session_issuer": {
                                                            "properties": {
                                                                "type":      {"type": "keyword"},
                                                                "arn":       {"type": "keyword"},
                                                                "account_id":{"type": "keyword"},
                                                                "user_name": {"type": "keyword"},
                                                            }
                                                        },
                                                        "mfa_authenticated": {"type": "keyword"},
                                                    }
                                                },
                                            }
                                        },
                                        # flattened allows arbitrary key/value structures
                                        "request_parameters":  {"type": "flattened"},
                                        "response_elements":   {"type": "keyword"},
                                        "additional_eventdata": {"type": "flattened"},
                                        "resources": {
                                            "type": "nested",
                                            "properties": {
                                                "arn":        {"type": "keyword"},
                                                "account_id": {"type": "keyword"},
                                                "type":       {"type": "keyword"},
                                            },
                                        },
                                        "console_login":  {"type": "keyword"},
                                        "read_only":      {"type": "boolean"},
                                        "management_event": {"type": "boolean"},
                                        "recipient_account_id": {"type": "keyword"},
                                    }
                                }
                            }
                        },
                    }
                }
            }
        },
    },

    # ------------------------------------------------------------------
    # Endpoint process component
    # ------------------------------------------------------------------
    {
        "name": "lab-endpoint.events.process@mappings",
        "body": {
            "template": {
                "mappings": {
                    "properties": {
                        "process": {
                            "properties": {
                                "name":         {"type": "keyword"},
                                "executable":   {"type": "keyword"},
                                "command_line": {"type": "keyword"},
                                "args":         {"type": "keyword"},
                                "pid":          {"type": "long"},
                                "working_directory": {"type": "keyword"},
                                "parent": {
                                    "properties": {
                                        "name":         {"type": "keyword"},
                                        "executable":   {"type": "keyword"},
                                        "command_line": {"type": "keyword"},
                                        "args":         {"type": "keyword"},
                                        "pid":          {"type": "long"},
                                    }
                                },
                                "hash": {
                                    "properties": {
                                        "sha256": {"type": "keyword"},
                                        "md5":    {"type": "keyword"},
                                    }
                                },
                                "user": {
                                    "properties": {
                                        "name": {"type": "keyword"},
                                        "id":   {"type": "keyword"},
                                    }
                                },
                            }
                        },
                    }
                }
            }
        },
    },

    # ------------------------------------------------------------------
    # Endpoint network component
    # ------------------------------------------------------------------
    {
        "name": "lab-endpoint.events.network@mappings",
        "body": {
            "template": {
                "mappings": {
                    "properties": {
                        "destination": {
                            "properties": {
                                "ip":     {"type": "ip"},
                                "port":   {"type": "integer"},
                                "domain": {"type": "keyword"},
                            }
                        },
                        "dns": {
                            "properties": {
                                "question": {
                                    "properties": {
                                        "name":                {"type": "keyword"},
                                        "registered_domain":   {"type": "keyword"},
                                        "type":                {"type": "keyword"},
                                        "subdomain":           {"type": "keyword"},
                                        "top_level_domain":    {"type": "keyword"},
                                    }
                                },
                                "resolved_ip": {"type": "ip"},
                                "type":        {"type": "keyword"},
                            }
                        },
                        "process": {
                            "properties": {
                                "name":       {"type": "keyword"},
                                "executable": {"type": "keyword"},
                                "parent": {
                                    "properties": {
                                        "name":       {"type": "keyword"},
                                        "executable": {"type": "keyword"},
                                    }
                                },
                            }
                        },
                        "network": {
                            "properties": {
                                "direction": {"type": "keyword"},
                                "protocol":  {"type": "keyword"},
                                "transport": {"type": "keyword"},
                                "type":      {"type": "keyword"},
                            }
                        },
                    }
                }
            }
        },
    },

    # ------------------------------------------------------------------
    # Endpoint file component
    # ------------------------------------------------------------------
    {
        "name": "lab-endpoint.events.file@mappings",
        "body": {
            "template": {
                "mappings": {
                    "properties": {
                        "file": {
                            "properties": {
                                "path":       {"type": "keyword"},
                                "name":       {"type": "keyword"},
                                "extension":  {"type": "keyword"},
                                "directory":  {"type": "keyword"},
                                "size":       {"type": "long"},
                                "type":       {"type": "keyword"},
                                "hash": {
                                    "properties": {
                                        "sha256": {"type": "keyword"},
                                        "md5":    {"type": "keyword"},
                                    }
                                },
                            }
                        },
                        "process": {
                            "properties": {
                                "name":       {"type": "keyword"},
                                "executable": {"type": "keyword"},
                                "parent": {
                                    "properties": {
                                        "name":       {"type": "keyword"},
                                        "executable": {"type": "keyword"},
                                    }
                                },
                            }
                        },
                    }
                }
            }
        },
    },
]

# ---------------------------------------------------------------------------
# Index templates
# ---------------------------------------------------------------------------

INDEX_TEMPLATES: list[dict[str, Any]] = [
    # ------------------------------------------------------------------
    # Kubernetes audit_logs
    # ------------------------------------------------------------------
    {
        "name": "logs-kubernetes.audit_logs",
        "body": {
            "index_patterns": ["logs-kubernetes.audit_logs-*"],
            "data_stream": {},
            "composed_of": [
                "lab-base@mappings",
                "lab-kubernetes.audit_logs@mappings",
            ],
            "priority": 200,
            "template": {
                "settings": {
                    "index": {
                        "number_of_shards": 1,
                        "number_of_replicas": 0,
                        "mapping": {
                            "total_fields": {"limit": 10000},
                        },
                    }
                },
                "mappings": {
                    "dynamic": True,
                },
            },
            "_meta": {
                "description": "Lab index template for Kubernetes audit logs – mirrors elastic/kubernetes integration",
                "managed_by": "agent-intrusion-lab",
            },
        },
    },

    # ------------------------------------------------------------------
    # AWS CloudTrail
    # ------------------------------------------------------------------
    {
        "name": "logs-aws.cloudtrail",
        "body": {
            "index_patterns": ["logs-aws.cloudtrail-*"],
            "data_stream": {},
            "composed_of": [
                "lab-base@mappings",
                "lab-aws.cloudtrail@mappings",
            ],
            "priority": 200,
            "template": {
                "settings": {
                    "index": {
                        "number_of_shards": 1,
                        "number_of_replicas": 0,
                        "mapping": {
                            "total_fields": {"limit": 10000},
                        },
                    }
                },
                "mappings": {
                    "dynamic": True,
                },
            },
            "_meta": {
                "description": "Lab index template for AWS CloudTrail – mirrors elastic/aws integration",
                "managed_by": "agent-intrusion-lab",
            },
        },
    },

    # ------------------------------------------------------------------
    # Endpoint process
    # ------------------------------------------------------------------
    {
        "name": "logs-endpoint.events.process",
        "body": {
            "index_patterns": ["logs-endpoint.events.process-*"],
            "data_stream": {},
            "composed_of": [
                "lab-base@mappings",
                "lab-endpoint.events.process@mappings",
            ],
            "priority": 200,
            "template": {
                "settings": {
                    "index": {
                        "number_of_shards": 1,
                        "number_of_replicas": 0,
                    }
                },
                "mappings": {
                    "dynamic": True,
                },
            },
            "_meta": {
                "description": "Lab index template for Elastic Defend process events",
                "managed_by": "agent-intrusion-lab",
            },
        },
    },

    # ------------------------------------------------------------------
    # Endpoint network
    # ------------------------------------------------------------------
    {
        "name": "logs-endpoint.events.network",
        "body": {
            "index_patterns": ["logs-endpoint.events.network-*"],
            "data_stream": {},
            "composed_of": [
                "lab-base@mappings",
                "lab-endpoint.events.network@mappings",
            ],
            "priority": 200,
            "template": {
                "settings": {
                    "index": {
                        "number_of_shards": 1,
                        "number_of_replicas": 0,
                    }
                },
                "mappings": {
                    "dynamic": True,
                },
            },
            "_meta": {
                "description": "Lab index template for Elastic Defend network events",
                "managed_by": "agent-intrusion-lab",
            },
        },
    },

    # ------------------------------------------------------------------
    # Endpoint file
    # ------------------------------------------------------------------
    {
        "name": "logs-endpoint.events.file",
        "body": {
            "index_patterns": ["logs-endpoint.events.file-*"],
            "data_stream": {},
            "composed_of": [
                "lab-base@mappings",
                "lab-endpoint.events.file@mappings",
            ],
            "priority": 200,
            "template": {
                "settings": {
                    "index": {
                        "number_of_shards": 1,
                        "number_of_replicas": 0,
                    }
                },
                "mappings": {
                    "dynamic": True,
                },
            },
            "_meta": {
                "description": "Lab index template for Elastic Defend file events",
                "managed_by": "agent-intrusion-lab",
            },
        },
    },

    # ------------------------------------------------------------------
    # Defend for Containers process  (cloud_defend.process)
    # ------------------------------------------------------------------
    {
        "name": "logs-cloud_defend.process",
        "body": {
            "index_patterns": ["logs-cloud_defend.process-*"],
            "data_stream": {},
            "composed_of": [
                "lab-base@mappings",
                "lab-endpoint.events.process@mappings",  # same field shape
            ],
            "priority": 200,
            "template": {
                "settings": {
                    "index": {
                        "number_of_shards": 1,
                        "number_of_replicas": 0,
                    }
                },
                "mappings": {
                    "dynamic": True,
                },
            },
            "_meta": {
                "description": "Lab index template for Defend for Containers process events",
                "managed_by": "agent-intrusion-lab",
            },
        },
    },

    # ------------------------------------------------------------------
    # Defend for Containers file  (cloud_defend.file)
    # ------------------------------------------------------------------
    {
        "name": "logs-cloud_defend.file",
        "body": {
            "index_patterns": ["logs-cloud_defend.file-*"],
            "data_stream": {},
            "composed_of": [
                "lab-base@mappings",
                "lab-endpoint.events.file@mappings",  # same field shape
            ],
            "priority": 200,
            "template": {
                "settings": {
                    "index": {
                        "number_of_shards": 1,
                        "number_of_replicas": 0,
                    }
                },
                "mappings": {
                    "dynamic": True,
                },
            },
            "_meta": {
                "description": "Lab index template for Defend for Containers file events",
                "managed_by": "agent-intrusion-lab",
            },
        },
    },
]

# ---------------------------------------------------------------------------
# Data stream names to explicitly bootstrap
# ---------------------------------------------------------------------------

DATA_STREAMS: list[str] = [
    f"logs-kubernetes.audit_logs-{DS_NAMESPACE}",
    f"logs-aws.cloudtrail-{DS_NAMESPACE}",
    f"logs-endpoint.events.process-{DS_NAMESPACE}",
    f"logs-endpoint.events.network-{DS_NAMESPACE}",
    f"logs-endpoint.events.file-{DS_NAMESPACE}",
    f"logs-cloud_defend.process-{DS_NAMESPACE}",
    f"logs-cloud_defend.file-{DS_NAMESPACE}",
]


# ---------------------------------------------------------------------------
# install_schema
# ---------------------------------------------------------------------------

def install_schema(es_client: Any) -> None:
    """
    Install all component templates, index templates, and bootstrap data streams.

    Parameters
    ----------
    es_client:
        An instantiated ``elasticsearch.Elasticsearch`` client (v8 API).
    """
    # 1. Component templates
    for ct in COMPONENT_TEMPLATES:
        name = ct["name"]
        body = ct["body"]
        logger.info("PUT component template: %s", name)
        es_client.cluster.put_component_template(name=name, **body)

    # 2. Index templates
    for it in INDEX_TEMPLATES:
        name = it["name"]
        body = it["body"]
        logger.info("PUT index template: %s", name)
        es_client.indices.put_index_template(name=name, **body)

    # 3. Data streams  – create explicitly so that the backing index is
    #    provisioned before any generator tries to write to it.
    for ds_name in DATA_STREAMS:
        try:
            logger.info("Creating data stream: %s", ds_name)
            es_client.indices.create_data_stream(name=ds_name)
        except Exception as exc:  # noqa: BLE001
            exc_str = str(exc).lower()
            if "resource_already_exists_exception" in exc_str or "already exists" in exc_str:
                logger.debug("Data stream already exists (skipped): %s", ds_name)
            else:
                raise


if __name__ == "__main__":
    import argparse
    from .esclient import make_es_client, load_env

    parser = argparse.ArgumentParser(description="Install schema for agent-intrusion-lab")
    parser.add_argument("--host", default=None)
    parser.add_argument("--api-key", default=None, dest="api_key")
    args = parser.parse_args()

    env = load_env()
    host = args.host or env.get("ES_HOST")
    api_key = args.api_key or env.get("ES_API_KEY")

    es = make_es_client(host, api_key)
    print("Installing component templates, index templates, and data streams...")
    install_schema(es)
    print(f"Schema installed. Data streams: {', '.join(DATA_STREAMS)}")
