"""
verify.py — Verification gate for the agent-intrusion-lab workshop.

Runs a suite of checks against Elasticsearch and Kibana and exits non-zero
if any required check fails.
"""

from __future__ import annotations

import re
import sys
from typing import Any, Dict, List, Optional, Tuple

from .esclient import make_es_client, kibana_request, load_env, get_es_version
from .rules import ARTICLE_RULES
from .schema import DATA_STREAMS

# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

_CORRELATION_BEATS = {"correlation"}

CheckResult = Tuple[str, bool, str]  # (label, passed, detail)


def _parse_version(version_str: str) -> Tuple[int, ...]:
    parts = re.split(r"[.\-]", version_str)
    result = []
    for p in parts[:3]:
        try:
            result.append(int(p))
        except ValueError:
            result.append(0)
    while len(result) < 3:
        result.append(0)
    return tuple(result)


def _kibana_get(path: str, api_key: str, kibana_url: str, public: bool = True, internal: bool = False) -> Any:
    return kibana_request(
        "GET",
        path,
        api_key=api_key,
        kibana_url=kibana_url,
        public=not internal,
    )


# ---------------------------------------------------------------------------
# Individual checks
# ---------------------------------------------------------------------------

def check_connectivity(es_client: Any, api_key: str, kibana_url: str) -> CheckResult:
    """ES GET / returns 200, Kibana GET /api/status returns 200."""
    try:
        es_client.info()
    except Exception as exc:
        return "Connectivity", False, f"Elasticsearch unreachable: {exc}"

    try:
        kibana_request("GET", "/api/status", api_key=api_key, kibana_url=kibana_url)
    except Exception as exc:
        return "Connectivity", False, f"Kibana unreachable: {exc}"

    return "Connectivity", True, "ES and Kibana both reachable"


def check_version(es_client: Any) -> CheckResult:
    """Stack version >= 9.3.0."""
    try:
        version = get_es_version(es_client)
    except Exception as exc:
        return "Version", False, f"Could not retrieve version: {exc}"

    if _parse_version(version) < _parse_version("9.3.0"):
        return "Version", False, f"Stack version {version} is below required 9.3.0"

    return "Version", True, f"Stack version {version} >= 9.3.0"


def check_schema(es_client: Any) -> CheckResult:
    """Each data stream in DATA_STREAMS exists."""
    missing = []
    for ds_name in DATA_STREAMS:
        try:
            es_client.indices.get_data_stream(name=ds_name)
        except Exception:
            missing.append(ds_name)

    if missing:
        return "Schema", False, f"Missing data streams: {', '.join(missing)}"

    return "Schema", True, f"All {len(DATA_STREAMS)} data streams exist"


def check_doc_counts(es_client: Any) -> CheckResult:
    """Each data stream has >= 1 doc. Warns on empty streams, prints counts."""
    empty = []
    counts: Dict[str, int] = {}

    for ds_name in DATA_STREAMS:
        try:
            resp = es_client.count(index=ds_name)
            count = resp.get("count", 0)
        except Exception as exc:
            print(f"  WARNING: Could not count docs in {ds_name}: {exc}")
            count = 0
        counts[ds_name] = count
        if count < 1:
            empty.append(ds_name)

    print("  Doc counts:")
    for ds_name, count in counts.items():
        flag = " (EMPTY)" if count == 0 else ""
        print(f"    {ds_name}: {count}{flag}")

    # cloud_defend streams are Defend for Containers events — not generated by
    # the synthetic campaign (they require real Elastic Defend agents). Treat as optional.
    optional_streams = {"logs-cloud_defend.process-workshop", "logs-cloud_defend.file-workshop"}
    required_empty = [s for s in empty if s not in optional_streams]

    if required_empty:
        return "Doc counts", False, f"Empty data streams: {', '.join(required_empty)}"

    return "Doc counts", True, f"All required data streams have >= 1 doc"


def check_freshness(es_client: Any) -> CheckResult:
    """MAX(@timestamp) across logs-kubernetes.audit_logs-* is within last 12 hours."""
    esql_query = (
        "FROM logs-kubernetes.audit_logs-* "
        "| STATS m = MAX(@timestamp) "
        "| EVAL age_h = DATE_DIFF(\"hours\", m, NOW()) "
        "| KEEP age_h"
    )

    try:
        resp = es_client.esql.query(query=esql_query, format="json")
    except Exception as exc:
        return "Freshness", False, f"ES|QL query failed: {exc}"

    rows = resp.get("values", [])
    if not rows or rows[0] is None or rows[0][0] is None:
        return "Freshness", False, "No docs in logs-kubernetes.audit_logs-*"

    age_h = rows[0][0]
    print(f"  Newest Kubernetes audit log: {age_h}h old")

    if age_h > 12:
        return "Freshness", False, f"Newest doc is {age_h}h old (limit: 12h)"

    return "Freshness", True, f"Newest doc is {age_h}h old (within 12h)"


def check_prebuilt_rules(api_key: str, kibana_url: str) -> CheckResult:
    """num_prebuilt_rules_to_install == 0."""
    try:
        status = kibana_request(
            "GET",
            "/internal/detection_engine/prebuilt_rules/status",
            api_key=api_key,
            kibana_url=kibana_url,
            public=False,
        )
    except Exception as exc:
        return "Prebuilt rules installed", False, f"Could not query prebuilt rules status: {exc}"

    # Response is nested: {"stats": {"num_prebuilt_rules_to_install": N, ...}, ...}
    if isinstance(status, dict) and "stats" in status:
        status = status["stats"]
    to_install = status.get("num_prebuilt_rules_to_install", -1)
    print(f"  Prebuilt rules to install: {to_install}")

    if to_install != 0:
        return (
            "Prebuilt rules installed",
            False,
            f"num_prebuilt_rules_to_install = {to_install} (expected 0)",
        )

    return "Prebuilt rules installed", True, "All prebuilt rules are installed"


def check_rules_enabled(api_key: str, kibana_url: str) -> CheckResult:
    """Each non-correlation rule in ARTICLE_RULES is enabled."""
    non_correlation = [r for r in ARTICLE_RULES if r.get("beat") not in _CORRELATION_BEATS]

    failures: List[str] = []
    for rule in non_correlation:
        rule_id = rule["rule_id"]
        name = rule["name"]
        try:
            resp = kibana_request(
                "GET",
                f"/api/detection_engine/rules?rule_id={rule_id}",
                api_key=api_key,
                kibana_url=kibana_url,
            )
            enabled = resp.get("enabled", False)
        except Exception as exc:
            enabled = False
            status = getattr(getattr(exc, "response", None), "status_code", None)
            if status == 404 or "404" in str(exc):
                print(f"  FAIL  {name} — not found")
            else:
                print(f"  FAIL  {name} — error: {exc}")
            failures.append(name)
            continue

        if enabled:
            print(f"  PASS  {name}")
        else:
            print(f"  FAIL  {name} — not enabled")
            failures.append(name)

    if failures:
        return (
            "Rules enabled",
            False,
            f"{len(failures)} rule(s) not enabled: {', '.join(failures[:3])}{'...' if len(failures) > 3 else ''}",
        )

    return "Rules enabled", True, f"All {len(non_correlation)} non-correlation rules are enabled"


def check_alert_count(es_client: Any) -> CheckResult:
    """10 <= alert count <= 2000 over last 9 days."""
    esql_query = (
        "FROM .alerts-security.alerts-* "
        "| WHERE @timestamp >= NOW() - 9 days "
        "| STATS c = COUNT(*) "
        "| KEEP c"
    )

    try:
        resp = es_client.esql.query(query=esql_query, format="json")
    except Exception as exc:
        return "Alert count", False, f"ES|QL query failed: {exc}"

    rows = resp.get("values", [])
    if not rows or rows[0] is None or rows[0][0] is None:
        count = 0
    else:
        count = rows[0][0]

    print(f"  Alert count (last 9 days): {count}")

    if count == 0:
        return "Alert count", False, "No alerts in .alerts-security.alerts-* (last 9 days) — run backfill"

    if count > 2000:
        return "Alert count", False, f"Alert count {count} exceeds expected max of 2000"

    if count < 10:
        print(f"  WARNING: Alert count {count} is low (target: 10-2000) — backfill may still be processing")

    return "Alert count", True, f"Alert count {count}"


def check_workshop_meta(es_client: Any) -> CheckResult:
    """workshop-meta index has a doc with campaign_start_ms, campaign_end_ms, anchor_ms."""
    try:
        resp = es_client.search(index="workshop-meta", size=1)
    except Exception as exc:
        return "workshop-meta", False, f"Could not query workshop-meta: {exc}"

    hits = resp.get("hits", {}).get("hits", [])
    if not hits:
        return "workshop-meta", False, "No document found in workshop-meta"

    doc = hits[0].get("_source", {})
    required_fields = ["campaign_start_ms", "campaign_end_ms", "anchor_ms"]
    missing = [f for f in required_fields if f not in doc]

    if missing:
        return (
            "workshop-meta",
            False,
            f"workshop-meta doc missing fields: {', '.join(missing)}",
        )

    return "workshop-meta", True, "workshop-meta doc has all required fields"


# ---------------------------------------------------------------------------
# Main verify function
# ---------------------------------------------------------------------------

def verify(
    host: str,
    api_key: str,
    kibana_url: Optional[str] = None,
    bulk_host: Optional[str] = None,
) -> int:
    """
    Run all verification checks.

    Returns 0 if all required checks pass, 1 otherwise.
    """
    if not kibana_url:
        import re as _re
        derived = _re.sub(r"\.es\.", ".kb.", host, count=1)
        kibana_url = derived

    # Always use ES_HOST (not bulk ingest endpoint) for queries
    es_client = make_es_client(host, api_key)

    results: List[CheckResult] = []

    print("\n--- 1. Connectivity ---")
    results.append(check_connectivity(es_client, api_key, kibana_url))

    print("\n--- 2. Version ---")
    results.append(check_version(es_client))

    print("\n--- 3. Schema ---")
    results.append(check_schema(es_client))

    print("\n--- 4. Doc counts ---")
    results.append(check_doc_counts(es_client))

    print("\n--- 5. Freshness ---")
    results.append(check_freshness(es_client))

    print("\n--- 6. Prebuilt rules installed ---")
    results.append(check_prebuilt_rules(api_key, kibana_url))

    print("\n--- 7. Rules enabled ---")
    results.append(check_rules_enabled(api_key, kibana_url))

    print("\n--- 8. Alert count ---")
    results.append(check_alert_count(es_client))

    print("\n--- 9. workshop-meta ---")
    results.append(check_workshop_meta(es_client))

    # Summary
    print("\n=== Verification Results ===")
    passed = sum(1 for _, ok, _ in results if ok)
    total = len(results)
    print(f"PASS: {passed}/{total} checks")

    failures = [(label, detail) for label, ok, detail in results if not ok]
    for label, detail in failures:
        print(f"FAIL: {label} — {detail}")

    exit_code = 0 if not failures else 1
    print(f"Exit code: {exit_code}")

    return exit_code


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Verify agent-intrusion-lab workshop setup")
    parser.add_argument("--host", help="Elasticsearch host URL (overrides ES_HOST env var)")
    parser.add_argument("--api-key", dest="api_key", help="API key (overrides ES_API_KEY env var)")
    parser.add_argument("--kibana-url", dest="kibana_url", help="Kibana URL (overrides KIBANA_URL env var)")
    parser.add_argument("--bulk-host", dest="bulk_host", help="Bulk ingest host URL (overrides ES_HOST_BULK env var)")
    args = parser.parse_args()

    try:
        env = load_env()
    except EnvironmentError as exc:
        if not args.host or not args.api_key:
            print(f"ERROR: {exc}", file=sys.stderr)
            sys.exit(2)
        env = {
            "ES_HOST": "",
            "ES_API_KEY": "",
            "ES_HOST_BULK": "",
            "KIBANA_URL": "",
        }

    host = args.host or env.get("ES_HOST", "")
    api_key = args.api_key or env.get("ES_API_KEY", "")
    kibana_url = args.kibana_url or env.get("KIBANA_URL") or None
    bulk_host = args.bulk_host or env.get("ES_HOST_BULK") or None

    if not host or not api_key:
        print("ERROR: ES_HOST and ES_API_KEY are required.", file=sys.stderr)
        sys.exit(2)

    exit_code = verify(host, api_key, kibana_url=kibana_url, bulk_host=bulk_host)
    sys.exit(exit_code)
